import type {
  AgencyLicenseType,
  BrokerLicenseType,
  ComplianceRegion,
  EnhancementTag,
  ListingPage,
  ListingStatus,
  MediaAsset,
} from "@/lib/db/schema";
import {
  AGENCY_LICENSE_TYPES,
  BROKER_LICENSE_TYPES,
  COMPLIANCE_REGIONS,
  ENHANCEMENT_TAGS,
  LISTING_STATUSES,
} from "@/lib/db/schema";

export const BROKER_LICENSE_LABELS: Record<BrokerLicenseType, { en: string; fr: string }> = {
  broker: { en: "Real estate broker", fr: "Courtier immobilier" },
  residential: { en: "Residential real estate broker", fr: "Courtier immobilier résidentiel" },
  commercial: { en: "Commercial real estate broker", fr: "Courtier immobilier commercial" },
  residential_commercial: {
    en: "Residential and commercial real estate broker",
    fr: "Courtier immobilier résidentiel et commercial",
  },
};

export const AGENCY_LICENSE_LABELS: Record<AgencyLicenseType, { en: string; fr: string }> = {
  agency: { en: "Real estate agency", fr: "Agence immobilière" },
  residential_agency: {
    en: "Residential real estate agency",
    fr: "Agence immobilière résidentielle",
  },
  commercial_agency: {
    en: "Commercial real estate agency",
    fr: "Agence immobilière commerciale",
  },
  residential_commercial_agency: {
    en: "Residential and commercial real estate agency",
    fr: "Agence immobilière résidentielle et commerciale",
  },
};

export const ENHANCEMENT_TAG_LABELS: Record<EnhancementTag, { en: string; fr: string }> = {
  virtually_staged: {
    en: "Virtually staged",
    fr: "Mise en scène virtuelle",
  },
  ai_generated: {
    en: "Image generated by artificial intelligence",
    fr: "Image générée par intelligence artificielle",
  },
  digitally_altered: {
    en: "Digitally altered image",
    fr: "Image modifiée numériquement",
  },
};

const PRICE_PATTERN =
  /(\$|€|£|usd|cad|asking\s+price|listed\s+at|list\s+price|sale\s+price|sold\s+for|%?\s*over\s+(asking|list)|asking\b)/i;

export function suggestComplianceRegion(postalOrZip: string | null | undefined): ComplianceRegion {
  const raw = (postalOrZip ?? "").trim().toUpperCase().replace(/\s+/g, "");
  if (!raw) return "ca_other";
  if (/^[GHJ]/.test(raw)) return "ca_qc";
  // US ZIP (5 digits) or ZIP+4 — California starts with 90–96
  if (/^\d{5}(-\d{4})?$/.test(raw)) {
    const prefix = Number(raw.slice(0, 2));
    if (prefix >= 90 && prefix <= 96) return "us_ca";
  }
  return "ca_other";
}

export function isComplianceRegion(value: string): value is ComplianceRegion {
  return (COMPLIANCE_REGIONS as readonly string[]).includes(value);
}

export function isListingStatus(value: string): value is ListingStatus {
  return (LISTING_STATUSES as readonly string[]).includes(value);
}

export function isBrokerLicenseType(value: string): value is BrokerLicenseType {
  return (BROKER_LICENSE_TYPES as readonly string[]).includes(value);
}

export function isAgencyLicenseType(value: string): value is AgencyLicenseType {
  return (AGENCY_LICENSE_TYPES as readonly string[]).includes(value);
}

export function isEnhancementTag(value: string): value is EnhancementTag {
  return (ENHANCEMENT_TAGS as readonly string[]).includes(value);
}

export function defaultAdvertisingEndsAt(fromIso: string, contractEndIso?: string | null) {
  if (contractEndIso?.trim()) return new Date(contractEndIso).toISOString();
  const base = new Date(fromIso);
  base.setUTCFullYear(base.getUTCFullYear() + 1);
  return base.toISOString();
}

export function listingContainsPrice(page: {
  headline?: string | null;
  description?: string | null;
  title?: string | null;
  sectionsJson?: string | null;
}) {
  const chunks = [
    page.headline ?? "",
    page.description ?? "",
    page.title ?? "",
    page.sectionsJson ?? "",
  ];
  return chunks.some((chunk) => PRICE_PATTERN.test(chunk));
}

export type PublishReadyInput = {
  page: Pick<
    ListingPage,
    | "agentName"
    | "agentEmail"
    | "brokerage"
    | "brokeragePhone"
    | "agentPhone"
    | "brandMode"
    | "complianceRegion"
    | "licenseDisplayName"
    | "licenseType"
    | "agencyLegalName"
    | "agencyLicenseType"
    | "advertisingEndsAt"
    | "headline"
    | "description"
    | "title"
    | "sectionsJson"
  >;
  media: Array<
    Pick<
      MediaAsset,
      "id" | "enhancementTag" | "originalDisclosureAssetId" | "disclosurePublic"
    >
  >;
};

export type PublishReadyResult =
  | { ok: true; alterationDisclaimer: boolean }
  | { ok: false; errors: string[] };

export function assertListingPublishReady(input: PublishReadyInput): PublishReadyResult {
  const errors: string[] = [];
  const { page, media } = input;

  if (!page.agentName?.trim()) errors.push("Agent name is required.");
  if (!page.agentEmail?.trim()) errors.push("Agent email is required.");
  if (!page.brokerage?.trim()) errors.push("Brokerage / agency name is required to publish.");
  const phone = page.brokeragePhone?.trim() || page.agentPhone?.trim();
  if (!phone) {
    errors.push("Brokerage or agent phone is required to publish.");
  }
  if (page.brandMode === "unbranded") {
    errors.push(
      "Public marketing pages must be branded so brokerage identity is visible. Switch brand mode to branded.",
    );
  }
  if (!page.advertisingEndsAt?.trim()) {
    errors.push("Brokerage contract end date (advertising window) is required.");
  }

  const tagged = media.filter((asset) => asset.enhancementTag);
  if (page.complianceRegion === "ca_qc") {
    if (!page.licenseDisplayName?.trim()) {
      errors.push("Licence display name (exact name on OACIQ licence) is required for Québec.");
    }
    if (!page.licenseType || !isBrokerLicenseType(page.licenseType)) {
      errors.push("Broker licence type is required for Québec.");
    }
    if (!page.agencyLegalName?.trim()) {
      errors.push("Full agency legal name is required for Québec.");
    }
    if (!page.agencyLicenseType || !isAgencyLicenseType(page.agencyLicenseType)) {
      errors.push("Agency licence type is required for Québec.");
    }
    if (listingContainsPrice(page)) {
      errors.push(
        "Québec advertising must not show sale or asking price (or figures that allow it to be deduced). Remove price language before publishing.",
      );
    }
  }

  if (page.complianceRegion === "us_ca" || tagged.length > 0) {
    for (const asset of tagged) {
      if (page.complianceRegion === "us_ca") {
        if (!asset.originalDisclosureAssetId?.trim()) {
          errors.push(
            `Altered image ${asset.id} needs a linked unaltered original for California disclosure.`,
          );
        } else {
          const counterpart = media.find((row) => row.id === asset.originalDisclosureAssetId);
          if (!counterpart || counterpart.disclosurePublic !== 1) {
            errors.push(
              `Unaltered original for ${asset.id} must be marked public for disclosure.`,
            );
          }
        }
      }
    }
  }

  if (errors.length > 0) return { ok: false, errors };
  return { ok: true, alterationDisclaimer: tagged.length > 0 };
}

/** True when the page should be served publicly. */
export function listingIsPubliclyLive(page: ListingPage, now = new Date()) {
  if (!page.publishedAt) return false;
  if (page.deedSignedAt) return false;
  if (page.advertisingEndsAt && new Date(page.advertisingEndsAt).getTime() < now.getTime()) {
    return false;
  }
  return true;
}

export type ListingPublicState =
  | "live"
  | "waiting_on_agent"
  | "draft"
  | "sold"
  | "ended"
  | "missing";

export type ListingPublicStateResult = {
  state: ListingPublicState;
  checklistErrors: string[];
};

/**
 * Single source of truth for why a listing page is or isn't publicly visible.
 * Pass media when available so compliance checklist errors are accurate.
 */
export function listingPublicState(
  page: ListingPage | null | undefined,
  media: PublishReadyInput["media"] = [],
  now = new Date(),
): ListingPublicStateResult {
  if (!page) return { state: "missing", checklistErrors: [] };

  if (page.deedSignedAt) {
    return { state: "sold", checklistErrors: [] };
  }
  if (
    page.advertisingEndsAt &&
    new Date(page.advertisingEndsAt).getTime() < now.getTime()
  ) {
    return { state: "ended", checklistErrors: [] };
  }

  const ready = assertListingPublishReady({ page, media });
  const checklistErrors = ready.ok ? [] : ready.errors;

  if (page.publishedAt) {
    return { state: "live", checklistErrors: [] };
  }
  if (checklistErrors.length > 0) {
    return { state: "waiting_on_agent", checklistErrors };
  }
  return { state: "draft", checklistErrors: [] };
}

export function listingStateLabel(state: ListingPublicState) {
  switch (state) {
    case "live":
      return "Live";
    case "waiting_on_agent":
      return "Waiting on agent";
    case "draft":
      return "Draft";
    case "sold":
      return "Sold";
    case "ended":
      return "Ended";
    case "missing":
      return "Not found";
  }
}

export function enhancementLabel(tag: EnhancementTag | null | undefined, lang: "en" | "fr") {
  if (!tag) return null;
  return ENHANCEMENT_TAG_LABELS[tag]?.[lang] ?? null;
}
